services:
  app:
    image: omar077/reoil:01.07.2023.00.31.14
    container_name: reoil
    restart: always
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/reoil
      - APP_URL=http://reoil.us-east-1.elasticbeanstalk.com
      - DISABLE_EMAIL_VERIFICATION=true
    depends_on:
      - postgres
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=reoil
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --locale=C
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always
volumes:
  postgres: