services:
  app:
    image: ghcr.io/omar-p/reoil:v3
    container_name: reoil
    restart: unless-stopped
    ports:
      - 8081:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/reoil
      - APP_URL=http://localhost
      - DISABLE_EMAIL_VERIFICATION=true
    depends_on:
      - postgres
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=reoil
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --locale=C
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: