logging.level.org.springframework.security=trace
spring.application.name=reoil
spring.messages.encoding=UTF-8
spring.messages.basename=messages


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=omar.dev.2000
spring.mail.password=knibgeiyxwgwwqey
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true