@startuml

title __MODEL's Class Diagram__\n

  namespace  {
    namespace du.tanta.fci.reoil {
      namespace user {
        namespace model {
          class edu.tanta.fci.reoil.user.model.AddressResponse {
              - address : String
              - fullName : String
              - id : Long
              - isMain : boolean
              - phoneNumber : String
              - title : String
              + AddressResponse()
              + address()
              + fullName()
              + id()
              + isMain()
              + phoneNumber()
              + title()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace du.tanta.fci.reoil {
      namespace user {
        namespace model {
          class edu.tanta.fci.reoil.user.model.Login {
              - email : String
              - password : String
              + Login()
              + email()
              + password()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace du.tanta.fci.reoil {
      namespace user {
        namespace model {
          class edu.tanta.fci.reoil.user.model.NewAddress {
              - address : String
              - firstName : String
              - isMain : boolean
              - lastName : String
              - phoneNumber : String
              - title : String
              + NewAddress()
              + address()
              + firstName()
              + isMain()
              + lastName()
              + phoneNumber()
              + title()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace du.tanta.fci.reoil {
      namespace user {
        namespace model {
          class edu.tanta.fci.reoil.user.model.Profile {
              - email : String
              - fullName : String
              - phoneNumber : String
              - points : Long
              - usedPoints : Long
              + Profile()
              + email()
              + fullName()
              + phoneNumber()
              + points()
              + usedPoints()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace du.tanta.fci.reoil {
      namespace user {
        namespace model {
          class edu.tanta.fci.reoil.user.model.ProfileUpdate {
              - email : String
              - fullName : String
              - phoneNumber : String
              + ProfileUpdate()
              + email()
              + fullName()
              + phoneNumber()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace du.tanta.fci.reoil {
      namespace user {
        namespace model {
          class edu.tanta.fci.reoil.user.model.RegistrationRequest {
              - email : String
              - password : String
              - passwordConfirmation : String
              - phoneNumber : String
              - username : String
              + RegistrationRequest()
              + email()
              + password()
              + passwordConfirmation()
              + phoneNumber()
              + username()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace du.tanta.fci.reoil {
      namespace user {
        namespace model {
          class edu.tanta.fci.reoil.user.model.UserProfile {
              - email : String
              - name : String
              - points : int
              + UserProfile()
              + email()
              + name()
              + points()
          }
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
