@startuml

title __ENTITIES's Class Diagram__\n

  namespace  {
    namespace du.tanta.fci.reoil {
      namespace user {
        namespace entities {
          class edu.tanta.fci.reoil.user.entities.Address {
              - address : String
              - fullName : String
              - id : Long
              - main : boolean
              - phoneNumber : String
              - title : String
              - version : int
              + Address()
              + Address()
              + getAddress()
              + getFullName()
              + getId()
              + getPhoneNumber()
              + getTitle()
              + getUser()
              + getVersion()
              + isMain()
              + setAddress()
              + setFullName()
              + setId()
              + setMain()
              + setPhoneNumber()
              + setTitle()
              + setUser()
              + setVersion()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace du.tanta.fci.reoil {
      namespace user {
        namespace entities {
          class edu.tanta.fci.reoil.user.entities.User {
              - addresses : List<Address>
              - authorities : Set<Authority>
              - createdAt : LocalDateTime
              - email : String
              - enabled : boolean
              - fullName : String
              - id : Long
              - password : String
              - phoneNumber : String
              - points : long
              - roles : Set<Role>
              - usedPoints : long
              - username : String
              - version : int
              + User()
              + User()
              + addAddress()
              + addRole()
              + getAddresses()
              + getAuthorities()
              + getCreatedAt()
              + getEmail()
              + getFullName()
              + getId()
              + getPassword()
              + getPhoneNumber()
              + getPoints()
              + getRoles()
              + getUsedPoints()
              + getUsername()
              + getVersion()
              + isAccountNonExpired()
              + isAccountNonLocked()
              + isCredentialsNonExpired()
              + isEnabled()
              + removeAddress()
              + setAddresses()
              + setAuthorities()
              + setCreatedAt()
              + setEmail()
              + setEnabled()
              + setFullName()
              + setId()
              + setPassword()
              + setPhoneNumber()
              + setPoints()
              + setRoles()
              + setUsedPoints()
              + setUsername()
              + setVersion()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace du.tanta.fci.reoil {
      namespace user {
        namespace entities {
          class edu.tanta.fci.reoil.user.entities.Verification {
              - id : String
              - username : String
              + Verification()
              + getId()
              + getUsername()
              # Verification()
          }
        }
      }
    }
  }
  

  edu.tanta.fci.reoil.user.entities.Address o-- edu.tanta.fci.reoil.user.entities.User : user
  edu.tanta.fci.reoil.user.entities.User .up.|> org.springframework.security.core.userdetails.UserDetails


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
